
num_clients: 10
number_of_rounds: 10
batch_size : 10
val_ratio : 0.1
target_clt: "Hospital"
num_class: 10
data_path: "./data"
tr_confg:
    lr: 0.001
    momentum: 0.1
    local_epochs: 1
